spring.application.name=perkpal
#spring.data.mongodb.uri=mongodb://localhost:27017/perkpal
server.port=${PORT:8080}
#spring.data.mongodb.uri=mongodb+srv://perkpaluser:Myperkpal123@perkpalcluster.oyfabvn.mongodb.net/perkpal?retryWrites=true&w=majority&appName=PerkpalCluster
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/perkpal}